server:
  port: 8088

logging:
  level:
    org.springframework : DEBUG

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    messages:
        basename: messages
#    security:
#        user:
#            name: user
#            password: 1234

    jpa:
        show-sql: true
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa


management:
    endpoints:
        web:
            exposure:
                include: "*"